Algoritmo "LaçoEnquanto"

Var
// Seção de Declarações das variáveis 
   i, x : inteiro  // Variavel i é padrão para iteração

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o valor inicial: ")
   leia(i)
   escreval("Digite o valor final: ")
   leia(x)
   escreval("INÍCIO DO LAÇO")
   enquanto i <= x faca
     escreval(i)
     i <- i + 1
   fimenquanto
   escreval("FIM DO LAÇO!!")

Fimalgoritmo