Algoritmo "Exercício_6"
// Fazer uma programa para aprensentar a divisão de dois números reais,

Var
// Seção de Declarações das variáveis 
   Numero_1, Numero_2, resultado: real

Inicio
// Entrada de dados
   escreva("Digite o primeiro número: ")
   leia(Numero_1)
   
   escreva("Digite o segundo número: ")
   leia(Numero_2)
   
// Processamento
   resultado <- Numero_1 / Numero_2
   // Saída:
   escreva("Resultado =", resultado)

Fimalgoritmo