Algoritmo "Exercício_2"
// Fazer um programa para ler dois números inteiros e apresentar a soma na
// tela.

Var
// Seção de Declarações das variáveis
   Numero_1, Numero_2, soma: inteiro
   
Inicio
   // Comando de entrada:
   escreva("Digite um número: ")
   leia(Numero_1)
   escreva("Digite outro número: ")
   leia(Numero_2)
   // Processamento:
   soma <- Numero_1 + Numero_2
   // Saída:
   escreval(Numero_1," +", Numero_2," =", soma)
   
Fimalgoritmo